comentarios_positivos = [
    "Produto de excelente qualidade, atendeu todas as minhas expectativas!",
    "Chegou antes do esperado, e o produto é ótimo!",
    "Muito bom, recomendo para todos que buscam qualidade e durabilidade.",
    "O design é incrível, estou encantado com o material.",
    "Funciona perfeitamente, valeu a pena cada centavo.",
    "Excelente custo-benefício, sem dúvida compraria de novo.",
    "Amei o produto, é exatamente o que eu queria!",
    "Produto de alta qualidade, vale o investimento.",
    "Serviço de atendimento foi ágil e eficiente, gostei muito.",
    "Fiquei super satisfeito com a compra, sem dúvida recomendo.",
    "Produto super bem embalado, chegou em perfeito estado.",
    "Ótima funcionalidade, valeu a pena o investimento.",
    "Comprei para um presente e foi um sucesso, todos adoraram!",
    "Entrega rápida, o produto chegou como esperado.",
    "Recomendo a todos, a qualidade é excepcional!",
    "O material é resistente e de ótima textura, estou muito feliz.",
    "Já comprei outros produtos dessa marca e sempre fico satisfeito!",
    "Muito bonito e bem feito, atendeu completamente às minhas necessidades.",
    "Preço justo, considerando a qualidade e a durabilidade do produto.",
    "Surpreendeu pela performance, estou utilizando há semanas sem nenhum problema.",
    "Produto perfeito, muito mais do que eu esperava.",
    "Chegou rapidamente e funciona muito bem, 5 estrelas!",
    "Recomendo, ótimo produto com ótimo preço!",
    "Funciona como prometido, estou muito satisfeito.",
    "Muito bem feito, e o preço foi muito acessível pela qualidade.",
    "Produto superou minhas expectativas, sem dúvida voltarei a comprar.",
    "Produto de alta durabilidade, já uso há meses e continua ótimo.",
    "Fiquei impressionado com o desempenho do produto.",
    "O atendimento foi excelente, a entrega foi rápida e eficiente.",
    "Simplesmente perfeito, atendeu todas as minhas necessidades.",
    "A embalagem foi muito bem feita e o produto chegou intacto.",
    "Muito satisfeito, não encontrei nenhum defeito.",
    "Funciona muito bem, e a entrega foi feita no prazo.",
    "Excelente produto! Eu simplesmente adoro!",
    "Produto de qualidade incrível, a marca está de parabéns.",
    "Recomendo de olhos fechados, vale muito a pena.",
    "Muito bom, não me arrependo da compra.",
    "Qualidade maravilhosa, vou comprar mais!",
    "Me surpreendeu pela praticidade e eficiência.",
    "Muito bom, e a entrega foi muito mais rápida do que eu esperava.",
    "Produto muito bom, chegou super rápido e está funcionando perfeitamente.",
    "Design moderno e qualidade de primeira, super recomendo.",
    "Entrega antes do prazo e produto impecável, ótimo!",
    "Fiquei super satisfeito com a compra, tudo perfeito.",
    "Recomendo para todos, produto de alta performance.",
    "Produto muito funcional e bonito. Amei a compra.",
    "Satisfeito com a compra, tudo de acordo com a descrição.",
    "Produto é perfeito, exatamente o que eu precisava.",
    "Excelente qualidade e durabilidade, vou comprar mais.",
    "Produto maravilhoso, valeu muito a pena a compra."
]

comentarios_negativos = [
    "Produto chegou danificado, não recomendo a compra.",
    "Não atendeu as expectativas, é de qualidade inferior.",
    "Pelo preço que cobram, esperava algo bem melhor.",
    "O material é muito frágil, não durou nem uma semana.",
    "Fiquei muito insatisfeito, o produto veio com defeito.",
    "A entrega foi muito demorada, e o atendimento não ajudou.",
    "Produto muito abaixo do esperado, não vale a pena.",
    "Infelizmente não funcionou como prometido, um total desperdício.",
    "Comprei confiando nas avaliações, mas o produto não vale o que custa.",
    "Péssima experiência, não voltarei a comprar.",
    "O produto não funciona corretamente, e o suporte ao cliente não resolveu nada.",
    "Muito caro pelo que oferece, me arrependi da compra.",
    "A embalagem estava toda danificada, um descaso com o cliente.",
    "Produto diferente do anunciado, totalmente decepcionante.",
    "Produto de baixa qualidade, não corresponde às descrições.",
    "Fiquei esperando por mais de 15 dias e o produto ainda não chegou.",
    "Não é o que eu esperava, muito abaixo das minhas expectativas.",
    "O material é barato e frágil, não vale o preço cobrado.",
    "Produto não funcionou direito, muito abaixo do que prometem nas imagens.",
    "Me arrependi completamente da compra, o produto não atende ao que é anunciado.",
    "Produto de péssima qualidade, já estragou depois de 1 mês de uso.",
    "Não vale o preço, muito fraco e mal feito.",
    "Entrega atrasada, não conseguiram me dar uma previsão.",
    "Comprei com uma expectativa muito alta, mas o produto deixou a desejar.",
    "Não gostei do produto, ele não é tão bom quanto o anunciado.",
    "Produto muito abaixo das expectativas, não recomendo.",
    "Não funciona como deveria, estou bastante decepcionado.",
    "O produto veio com defeito, não estou satisfeito.",
    "A entrega foi péssima, demorou e o produto veio com avarias.",
    "O produto não tem a qualidade que prometem.",
    "Produto não era como nas fotos, fiquei muito decepcionado.",
    "Fiquei muito frustrado com a compra, não recomendo.",
    "Não comprem, o produto é muito inferior ao que eu imaginava.",
    "O produto não serve para o que é proposto, uma grande decepção.",
    "Fiquei esperando o produto por dias e quando chegou não funcionou.",
    "Não cumpre o que promete, esperava bem mais.",
    "Produto não é funcional, e o atendimento é péssimo.",
    "Tentei entrar em contato com o suporte, mas não obtive ajuda.",
    "Não gostei do material, parece muito frágil.",
    "Achei o preço muito alto para a qualidade do produto.",
    "O produto falhou logo nos primeiros dias de uso.",
    "Não recomendo, o produto não funcionou para mim.",
    "Produto com defeito e péssimo atendimento, me arrependi.",
    "Não vale o que cobram por ele, produto bem abaixo da expectativa.",
    "Comprei acreditando nas avaliações, mas não vale a pena.",
    "Não gostei do acabamento, veio com marcas de fabricação.",
    "Fiquei decepcionado, o produto não correspondeu à descrição.",
    "Esperava muito mais pelo preço pago, me senti enganado.",
    "Produto veio com defeito, o atendimento não foi útil.",
    "Comprei, usei uma vez e já deu defeito, não recomendo."
]